// <auto-generated />
namespace SongHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populateGenresTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateGenresTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804202132319_populateGenresTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
